name: CI
on:
  push:
    tags: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build -t '${{secrets.DOCKER_USERNAME}}'/repository_pipeline:'${{github.sha}}' .
    - name: Login to Docker hub
      run: docker login --username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'
    - name: Push the image to docker hub
      run: docker push '${{secrets.DOCKER_USERNAME}}'/repository_pipeline:'${{github.sha}}'
